language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t sanjaypsachdev/docker-react -f Dockerfile.dev .

scripts:
  - docker run sanjaypsachdev/docker-react yarn test -- --coverage